### ISSUE TITLE
Issues with Vanilla

### ISSUE THREAD

**Issue by Tronald** [Xilophor/LethalNetworkAPI#12]
Seemed like the API was working with vanilla just a couple days ago, but now I can't connect to any lobbies unless they also have LethalNetworkAPI. Not sure what happened.

**Comment by Xilophor** [comment]
With the way this API is programmed - using network prefabs - it never had compatibility with lobbies that didn't have this mod installed. Any compatibility with joining was coincidental, and not something that I'd like to support; as doing so would require an entire rewrite of the API's back-end.

**Comment by Tronald** [comment]
Makes sense thanks for the update. Not sure how it connected in my tests, but maybe the other person had LethalNetworkAPI running too, which would make sense. Appreciate the response. Great tool BTW thank you.
