### ISSUE TITLE
Networking bricks itself after host disconnects

### ISSUE THREAD

**Issue by Fandovec03** [Xilophor/LethalNetworkAPI#31]
While testing my implementation of the API whenever host disconnects and end the session a NRE error shows up and they will not be able to host until they completely restart the game. I don't know if it might be an issue how I use the API but it looks like an issue with network Variables.

[LogOutput.log](https://github.com/user-attachments/files/18256686/LogOutput.log)

**Comment by funfoxrr** [comment]
I'm having the same issue, I currently have been chatting with the creator on discord and we're trying to figure it out... I'll make sure to let you know what happens. (Also #30 is simular to this)

**Comment by Xilophor** [comment]
Resolved in v3.3.2
